### ISSUE TITLE
Add -binobj key to delete "bin\obj" folders quick

### ISSUE THREAD

**Issue by LightVolk** [sebnilsson/DotnetCleanup#3]
Add -binobj key to delete "bin\obj" folders quick.

This will be like this:

cleanup -binobj

**Comment by sebnilsson** [comment]
Hello @LightVolk. This is a bit too niche to implement in this project. I'd recommend that you just create your own alias:
https://sebnilsson.com/blog/powershell-linq-with-short-aliases/
