### ISSUE TITLE
[Question] Difference to dotnet clean

### ISSUE THREAD

**Issue by lonix1** [sebnilsson/DotnetCleanup#6]
How does this tool differ to `dotnet clean`?

**Comment by sebnilsson** [comment]
@lonix1 `dotnet clean` removes the content in the `bin` and `obj`-folders, if I understand it correctly.

This tool does more than that, including removing `node_modules`, but it does it much faster, by moving the files to a temp-folder first and then removing them, so you can continue working without waiting for the delete-process.
